name: distributed-systems-lab-1

version: '3.4'
services:
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: ./manager/Dockerfile

    ports:
      - "13001:8000"

    environment:
      - MANAGER_SERVER_HOST=0.0.0.0
      - MANAGER_SERVER_PORT=8000
      - MANAGER_WORKERS_TASK_SIZE=10000000
      - MANAGER_WORKERS_LIST=worker-1:8000:worker-2:8000:worker-3:8000


  worker-1:
    container_name: worker-1
    build:
      context: .
      dockerfile: ./worker/Dockerfile

    ports:
      - "13002:8000"

    environment:
      - WORKER_SERVER_HOST=0.0.0.0
      - WORKER_SERVER_PORT=8000
      - WORKER_MANAGER_HOST=manager
      - WORKER_MANAGER_PORT=8000

  worker-2:
    container_name: worker-2
    build:
      context: .
      dockerfile: ./worker/Dockerfile

    ports:
      - "13003:8000"

    environment:
      - WORKER_SERVER_HOST=0.0.0.0
      - WORKER_SERVER_PORT=8000
      - WORKER_MANAGER_HOST=manager
      - WORKER_MANAGER_PORT=8000

  worker-3:
    container_name: worker-3
    build:
      context: .
      dockerfile: ./worker/Dockerfile

    ports:
      - "13004:8000"

    environment:
      - WORKER_SERVER_HOST=0.0.0.0
      - WORKER_SERVER_PORT=8000
      - WORKER_MANAGER_HOST=manager
      - WORKER_MANAGER_PORT=8000
