server:
  host: localhost
  port: 8001
manager:
  host: localhost
  port: 8000
rabbitmq:
  connStr: amqp://rmuser:rmpassword@rabbitmq:5672/crackHash
  taskExchange: tasks
  taskQueue: tasks_queue
  resultExchange: results
